
    type Book {
        title: String
        author: String
    }

    type Post {
        author: ID
        comment: String
    }

    type Query {
        books: [Book]
    }

    type Mutation {
        makePost(author:String, comment:String, deleted:Boolean ): Post
    }

    type Subscription {
        postCreated: Post
    }
