type Query {
  logIn(username: String!, password: String!): Authentication
}

type Mutation {
  test: String
}

type Subscription {
  test: String
}

type Authentication {
  token: String!
}

directive @auth(role: AuthenticationRole = ADMIN) on OBJECT | FIELD_DEFINITION

enum AuthenticationRole {
  ADMIN
  USER
}
